main_url = 'https://stellarburgers.nomoreparties.site/'
login_url = 'https://stellarburgers.nomoreparties.site/login'
forgot_password_url = 'https://stellarburgers.nomoreparties.site/forgot-password'
reset_password_url = 'https://stellarburgers.nomoreparties.site/reset-password'
account_url = 'https://stellarburgers.nomoreparties.site/account'
history_orders_url = 'https://stellarburgers.nomoreparties.site/account/order-history'
lenta_url = 'https://stellarburgers.nomoreparties.site/feed'